//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueMaster.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeagueMaster.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;positions&gt;
        ///  &lt;!-- Location to click ingame to avoid AFKing--&gt;
        ///  &lt;position id=&quot;anti_afk&quot;&gt;
        ///    &lt;x&gt;575&lt;/x&gt;
        ///    &lt;y&gt;483&lt;/y&gt;y
        ///  &lt;/position&gt;
        ///
        ///  &lt;!-- Middle of the &quot;Play Again&quot; button to requeue--&gt;
        ///  &lt;position id=&quot;play_again_button&quot;&gt;
        ///    &lt;x&gt;1160&lt;/x&gt;
        ///    &lt;y&gt;740&lt;/y&gt;
        ///  &lt;/position&gt;
        ///
        ///  &lt;!-- Middle of the leave game button at endgame screen--&gt;
        ///  &lt;position id=&quot;end_game_button&quot;&gt;
        ///    &lt;x&gt;710&lt;/x&gt;
        ///    &lt;y&gt;583&lt;/y&gt;
        ///  &lt;/position&gt;
        ///
        ///  &lt;!-- Middle of the ok button on the level-up notification popup--&gt;
        ///  &lt;positi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _1024x600 {
            get {
                return ResourceManager.GetString("_1024x600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;positions&gt;
        ///  &lt;!-- Location to click ingame to avoid AFKing--&gt;
        ///  &lt;position id=&quot;anti_afk&quot;&gt;
        ///    &lt;x&gt;575&lt;/x&gt;
        ///    &lt;y&gt;483&lt;/y&gt;y
        ///  &lt;/position&gt;
        ///
        ///  &lt;!-- Middle of the &quot;Play Again&quot; button to requeue--&gt;
        ///  &lt;position id=&quot;play_again_button&quot;&gt;
        ///    &lt;x&gt;1160&lt;/x&gt;
        ///    &lt;y&gt;740&lt;/y&gt;
        ///  &lt;/position&gt;
        ///
        ///  &lt;!-- Middle of the leave game button at endgame screen--&gt;
        ///  &lt;position id=&quot;end_game_button&quot;&gt;
        ///    &lt;x&gt;710&lt;/x&gt;
        ///    &lt;y&gt;583&lt;/y&gt;
        ///  &lt;/position&gt;
        ///
        ///  &lt;!-- Middle of the ok button on the level-up notification popup--&gt;
        ///  &lt;positi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _1440x900 {
            get {
                return ResourceManager.GetString("_1440x900", resourceCulture);
            }
        }
    }
}
